package com.KlochkovDm.gitapp.domain

import com.KlochkovDm.gitapp.domain.entities.UserProfile

class MockUserRepositoryImpl : UserRepository {

    override fun getUserList(): List<UserProfile> = listOf(
        UserProfile(
            "User1",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User2",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User3",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User4",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User5",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User6",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User7",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User8",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User9",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        ),
        UserProfile(
            "User10",
            "https://cdn.pixabay.com/photo/2017/11/10/05/46/group-2935521_960_720.png",
            listOf(
                "Repo1",
                "Repo2",
                "Repo3",
                "Repo4",
                "Repo5",
                "Repo6",
                "Repo7",
                "Repo8",
                "Repo9",
                "Repo10"
            )
        )
    )
}